name: GhienAI-Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: GhienAI-Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /root/GhienAI-Production/GhienAI-Server
            
            git pull origin main
            
            docker build -t backend-prod .
            
            docker stop backend-container || true
            docker rm backend-container || true
            
            docker run -d \
              -p 3001:3001 \
              --name backend-container \
              backend-prod
